section02/section01/Models/Band.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace section01.Models
{
    public class Band
    {
        [Display(Name="Name og the musican")]
        public string Title { get; set; }
        [Display(Name = "Name og the gendre")]
        public string Gendre { get; set; }
        [Display(Name = "Name og the origin")]
        public string Origin { get; set; }
        
        public string Biography { get; set; }
    }
}

section02/section01/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace section01.Models
{
    public class Book
    {
        public string Title { get; set; }
        public string Author { get; set; }
    }
}

section02/section01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using section01.Models;

namespace section01.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index(int id)
        {
            var newUpMyModel = new Book
            {
                Title = "Hi There, world",
                Author = "Random Human"
            };

            return View(newUpMyModel);
        }
    }
}

section02/section01/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using section01.Models;

namespace section01.Controllers
{
    public class MusicController : Controller
    {
        // GET: Music
        public ActionResult Index()
        {
            return View();
        }

        // GET: Music/Details/5
        public ActionResult Details(int id)
        {
            var band = new Band
            {
                Title = "Test",
                Biography = "Should woks",
                Origin = "Your moms grage",
                Gendre = "Garage rock"
            };
            return View(band);
        }

        public JsonResult TestGetBand()
        {
            var band = new Band
            {
                Title = "Newiest band",
                Biography = "Should woks better than earlier",
                Origin = "Your father grage",
                Gendre = "Garage rock"
            };
            return Json(JsonConvert.SerializeObject(band));
        }

        // GET: Music/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Music/Create
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Create([FromBody]Band band)
        {
            try
            {
                // TODO: Add insert logic here

                // return RedirectToAction(nameof(Index));
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Music/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Music/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Music/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Music/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

section02/section01/Views/Home/Index.cshtml
@model section01.Models.Book;

@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Parallax Template - Materialize</title>
	<!-- CSS  -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
	<link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
</head>
<body>
	<nav class="white" role="navigation">
		<div class="nav-wrapper container">
			<a id="logo-container" href="#" class="brand-logo">Logo</a>
			<ul class="right hide-on-med-and-down">
				<li><a href="#">Navbar Link</a></li>
			</ul>
			<ul id="nav-mobile" class="sidenav">
				<li><a href="#">Navbar Link</a></li>
			</ul>
			<a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		</div>
	</nav>
	<div id="index-banner" class="parallax-container">
		<div class="section no-pad-bot">
			<div class="container">
				<br><br>
				<h1 class="header center teal-text text-lighten-2">Parallax Template</h1>
				<div class="row center">
					<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
				</div>
				<div class="row center">
					<a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
				</div>
				<br><br>
			</div>
		</div>
		<div class="parallax"><img src="background1.jpg" alt="Unsplashed background img 1"></div>
	</div>

	<div class="container">
		<div class="section">
			<!--   Icon Section   -->
			<div class="row">
				<div class="col s12 m4">
					<div class="icon-block">
						<h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
						<h5 class="center">Speeds up development</h5>
						<p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
					</div>
				</div>
				<div class="col s12 m4">
					<div class="icon-block">
						<h2 class="center brown-text"><i class="material-icons">group</i></h2>
						<h5 class="center">User Experience Focused</h5>
						<p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
					</div>
				</div>
				<div class="col s12 m4">
					<div class="icon-block">
						<h2 class="center brown-text"><i class="material-icons">settings</i></h2>
						<h5 class="center">Easy to work with</h5>
						<p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="parallax-container valign-wrapper">
		<div class="section no-pad-bot">
			<div class="container">
				<div class="row center">
					<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
				</div>
			</div>
		</div>
		<div class="parallax"><img src="background2.jpg" alt="Unsplashed background img 2"></div>
	</div>
	<div class="container">
		<div class="section">
			<div class="row">
				<div class="col s12 center">
					<h3><i class="mdi-content-send brown-text"></i></h3>
					<h4>Contact Us</h4>
					<p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
				</div>
			</div>
		</div>
	</div>

	<div class="parallax-container valign-wrapper">
		<div class="section no-pad-bot">
			<div class="container">
				<div class="row center">
					<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
				</div>
			</div>
		</div>
		<div class="parallax"><img src="background3.jpg" alt="Unsplashed background img 3"></div>
	</div>
	<footer class="page-footer teal">
		<div class="container">
			<div class="row">
				<div class="col l6 s12">
					<h5 class="white-text">Company Bio</h5>
					<p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>

				</div>
				<div class="col l3 s12">
					<h5 class="white-text">Settings</h5>
					<ul>
						<li><a class="white-text" href="#!">Link 1</a></li>
						<li><a class="white-text" href="#!">Link 2</a></li>
						<li><a class="white-text" href="#!">Link 3</a></li>
						<li><a class="white-text" href="#!">Link 4</a></li>
					</ul>
				</div>
				<div class="col l3 s12">
					<h5 class="white-text">Connect</h5>
					<ul>
						<li><a class="white-text" href="#!">Link 1</a></li>
						<li><a class="white-text" href="#!">Link 2</a></li>
						<li><a class="white-text" href="#!">Link 3</a></li>
						<li><a class="white-text" href="#!">Link 4</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="footer-copyright">
			<div class="container">
				Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
			</div>
		</div>
	</footer>

	<!--  Scripts-->
	<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="js/materialize.js"></script>
	<script src="js/init.js"></script>
</body>
</html>

section02/section01/Views/Music/Add.cshtml
@model section01.Models.Band

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

<div>
    <h4>Band</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gendre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gendre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Biography)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Biography)
        </dd>
    </dl>
    
    <form asp-action="Add">
        <input type="submit" value="Add" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

section02/section01/Views/Music/Create.cshtml
@model section01.Models.Band

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Band</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		@using (Html.BeginForm("Create", "Music"))
		{

			<!--
		<form asp-controller="Music" asp-action="Create" method="post">
		<form asp-action="Create">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		-->
			<div class="form-group">
				<!--
			<label asp-for="Title" class="control-label">our value</label>
			<input asp-for="Title" class="form-control" />
			<span asp-validation-for="Title" class="text-danger"></span>
			-->
				@Html.LabelFor(x => x.Title) <br />
				@Html.TextBoxFor(x => x.Title) <br />
				@Html.ValidationMessageFor(x => x.Title)<br />

			</div>
			<div class="form-group">
				@Html.LabelFor(x => x.Gendre)<br />
				@Html.TextBoxFor(x => x.Gendre)<br />
				@Html.ValidationMessageFor(x => x.Gendre)<br />

				<!--
			<label asp-for="Gendre" class="control-label"></label>
			<input asp-for="Gendre" class="form-control" />
			<span asp-validation-for="Gendre" class="text-danger"></span>
			-->
			</div>
			<div class="form-group">
				<!--
			<label asp-for="Origin" class="control-label"></label>
			<input asp-for="Origin" class="form-control" />
			<span asp-validation-for="Origin" class="text-danger"></span>
			-->
				@Html.LabelFor(x => x.Origin)<br />
				@Html.TextBoxFor(x => x.Origin)<br />
				@Html.ValidationMessageFor(x => x.Origin)<br />

			</div>
			<div class="form-group">
				<!--
			<label asp-for="Biography" class="control-label"></label>
			<input asp-for="Biography" class="form-control" />
			<span asp-validation-for="Biography" class="text-danger"></span>
			-->
				@Html.LabelFor(x => x.Biography)<br />
				@Html.TextAreaFor(x => x.Biography)<br />
				@Html.ValidationMessageFor(x => x.Biography)<br />

			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		}
	</div>
	</div>

	<div>
		<a asp-action="Index">Back to List</a>
	</div>

section02/section01/Views/Music/Details.cshtml
@model section01.Models.Band

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="container">
	<div class="row">
		<div class="col-md-6">

		<h4>Band</h4>
		<hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.Title)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Title)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Gendre)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Gendre)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Origin)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Origin)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Biography)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Biography)
			</dd>
		</dl>

	</div>
			<div id="data"></div>
		
	</div>
		<button id="ajaxTest">Ajax Get</button>
		
	</div>
</div>

<script>
	var data = {
		title = "yclod",
		genre = "gendre",
		origin = "parent garage",
		biography = "Hot rock music"
	}
	fetch('/music/create', {
		method: 'POST',
		body: JSON.stringify(data),
		headrs: {
			"Accept": "application/json",
			"Content-Type":"application/json"
		}
		body: data
	})
		.then(function (response) {
			return response.json();
		})
		.then(function (myJson) {
			console.log(myJSON);
		});
</script>

section02/section01/Views/Music/Index.cshtml
@model IEnumerable<section01.Models.Band>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gendre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Biography)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gendre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Origin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Biography)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

section02/section01/Views/Shared/_Layout .cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>@ViewBag.Title</title>
	<!-- Compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

	<!-- Compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Parallax Template - Materialize</title>
		<!-- CSS  -->
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link href="~css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
		<link href="~css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
	</head>
	<body>
		<nav class="white" role="navigation">
			<div class="nav-wrapper container">
				<a id="logo-container" href="#" class="brand-logo">Logo</a>
				<ul class="right hide-on-med-and-down">
					<li><a href="#">Navbar Link</a></li>
				</ul>
				<ul id="nav-mobile" class="sidenav">
					<li><a href="#">Navbar Link</a></li>
				</ul>
				<a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
			</div>
		</nav>
		<div id="index-banner" class="parallax-container">
			<div class="section no-pad-bot">
				<div class="container">
					<br><br>
					<h1 class="header center teal-text text-lighten-2">Parallax Template</h1>
					<div class="row center">
						<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
					</div>
					<div class="row center">
						<a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
					</div>
					<br><br>
				</div>
			</div>
			<div class="parallax"><img src="background1.jpg" alt="Unsplashed background img 1"></div>
		</div>

		<div class="container">
			<div class="section">
				<!--   Icon Section   -->
				<div class="row">
					<div class="col s12 m4">
						<div class="icon-block">
							<h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
							<h5 class="center">Speeds up development</h5>
							<p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
						</div>
					</div>
					<div class="col s12 m4">
						<div class="icon-block">
							<h2 class="center brown-text"><i class="material-icons">group</i></h2>
							<h5 class="center">User Experience Focused</h5>
							<p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
						</div>
					</div>
					<div class="col s12 m4">
						<div class="icon-block">
							<h2 class="center brown-text"><i class="material-icons">settings</i></h2>
							<h5 class="center">Easy to work with</h5>
							<p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="parallax-container valign-wrapper">
			<div class="section no-pad-bot">
				<div class="container">
					<div class="row center">
						<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
					</div>
				</div>
			</div>
			<div class="parallax"><img src="background2.jpg" alt="Unsplashed background img 2"></div>
		</div>
		<div class="container">
			<div class="section">
				<div class="row">
					<div class="col s12 center">
						<h3><i class="mdi-content-send brown-text"></i></h3>
						<h4>Contact Us</h4>
						<p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
					</div>
				</div>
			</div>
		</div>

		<div class="parallax-container valign-wrapper">
			<div class="section no-pad-bot">
				<div class="container">
					<div class="row center">
						<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
					</div>
				</div>
			</div>
			<div class="parallax"><img src="background3.jpg" alt="Unsplashed background img 3"></div>
		</div>
		<footer class="page-footer teal">
			<div class="container">
				<div class="row">
					<div class="col l6 s12">
						<h5 class="white-text">Company Bio</h5>
						<p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>

					</div>
					<div class="col l3 s12">
						<h5 class="white-text">Settings</h5>
						<ul>
							<li><a class="white-text" href="#!">Link 1</a></li>
							<li><a class="white-text" href="#!">Link 2</a></li>
							<li><a class="white-text" href="#!">Link 3</a></li>
							<li><a class="white-text" href="#!">Link 4</a></li>
						</ul>
					</div>
					<div class="col l3 s12">
						<h5 class="white-text">Connect</h5>
						<ul>
							<li><a class="white-text" href="#!">Link 1</a></li>
							<li><a class="white-text" href="#!">Link 2</a></li>
							<li><a class="white-text" href="#!">Link 3</a></li>
							<li><a class="white-text" href="#!">Link 4</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="footer-copyright">
				<div class="container">
					Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
				</div>
			</div>
		</footer>

		<!--  Scripts-->
		<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script src="js/materialize.js"></script>
		<script src="js/init.js"></script>
	</body>
</html>


<div class="container">
	@RenderBody()
</div>


</body>
</html>